spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000

  main:
    lazy-initialization: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    validate-on-migrate: true

  thymeleaf:
    cache: true

logging:
  level:
    root: WARN
    org.springframework: INFO