spring:
  application:
    name: notes-service

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true